### PR TITLE
Bugfix - Sidebar Animation in Mobile Mode

### PR DESCRIPTION
**Pull request by julianpoy**
Default CSS was incorrect and unrecognizable to the browser. Fixed with new class.
Closes #2.

### CODE REVIEW

**Comment by zachlatta** [comment]
What do you mean by the default CSS was incorrect? Is this a bug in Foundation?

**Comment by julianpoy** [comment]
Yes, it is a bug in foundation. This CSS element for the movement of the side drawer is invalid CSS for most browsers. I simply added a class to override it with universally acceptable CSS.

Invalid inbuilt CSS:
transition: transform 500ms ease;

Override CSS:
transition: .4s ease;

**Comment by zachlatta** [comment]
I'm having trouble reproducing this issue on the latest Chrome, Firefox and mobile Chrome on Android.

What's the environment you're reproducing this in?

**Comment by julianpoy** [comment]
This is a very strange bug, since I have been able to replicate it but only on certain GIT versions. Since this seems to resolve itself whenever GIT is updated from the previous master version in any way, there is no need to pursue a fix.

Issue is now closed.

**Pull request closed without merging**
